adobe/aio-theme

packages/gatsby-theme-parliament/src/components/OpenAPIBlock.js
Adds a bunch of CSS to make over ReDoc with a spectrum theme. 
n/a
I feel like we can merge this in now and I'll continue to pick away at it as we find more things that don't look quite right.
Running `gatsby dev` in this project.
=> Style OpenAPI pages with Spectrum

packages/gatsby-theme-parliament/src/components/OpenAPIBlock.js
Enhances the OpenAPIBlock to be able to accept a spec object as well as a spec url.
n/a
Flexibility mostly. Having the spec in the project will enable it to be enhanced with things like code samples and will enable easier searching.
I whipped through the specs at: https://github.com/OAI/OpenAPI-Specification/tree/master/examples
Passing them in as `specUrl` and `spec`.
n/a the page looks the same regardless of the input.
=> 🎉  Support passing spec a JSON object

README.md
=> fix: add Publishing workflow to README

example/src/pages/index.md, packages/gatsby-theme-aio/package.json, yarn.lock
Updates the `gatsby-plugin-mdx` dependency to 2.5.0, which contains my reference style link bugfix (https://github.com/gatsbyjs/gatsby/pull/30967).
Closes #305 
Enables reference-style links for documentation projects that currently or may use it.
1. Converted an inline link in the root `index.md` page into a reference style link.
2. Created a production build with prefix and pointed the HTTP server to the build artifacts: `yarn start:prefix`
3. Navigated to http://localhost:9000/example/ 
4. Verified the **contributing page** link destination contains the `example` base URL
=> Feature: Enable reference style links

.gitignore, packages/gatsby-theme-aio/gatsby-node.js, packages/gatsby-theme-aio/src/components/JsDocParameters/index.js
This PR adds Gatsby `resolvers` in order to fix problems with the GraphQL query we use within the `query-builder.js`.  It also adds Gatsby's helper function `withPrefix` to create a link I can use on the frontend for search results.
This PR defines the three missing fields we use for our search records: `description`, `contributors`, and `keywords`. These three fields must be defined explicitly because we use them in our search code and we don't want sites failing to build if they don't define one or more of these fields in their frontmatter. 
For example: The `uxp-photoshop` site failed to build when running tests for search indexing because there was not a single entry of the field `keywords` within the frontmatter of any `md` files. So not even the implicit schema contained `keywords`. …
=> Fixed Frontmatter: Added resolvers to extend MdxFrontmatter fields properly

packages/gatsby-theme-aio/src/components/Code/index.js
When getting the list of tokens from prism, the Code component currently does this:
```
const lines = tokens.slice(0, -1);
```
(it actually does this twice, but I'll get to that)
This assumes that the last item in the `tokens` array is empty and _should_ be removed. This change first checks that the last item is empty and only removes it _if_ it is empty.
In the current implementation, the slice is actually done two times:
* Once to determine if there's multiple lines.
* Once when iterating through the tokens to output them for display.
In order to avoid duplication, I removed the second slice and just used the (potentially) modified `lines` array that is used to determine if multiple lines are present.
#505 
Manual testing
=> fix(code): only remove last token when the last token is blank. fixes #505

packages/gatsby-theme-aio/src/components/SEO/index.js
Previously analytics bootstrap script was only loaded based on two env variables that are not present. This cleans up the logic and should cause analytics script to run when both this and https://github.com/AdobeDocs/dev-site/pull/99 are merged.
Switching to global nav.
It hasn't!
=> Cleaning up logic to include analytics bootstrap script

packages/gatsby-theme-aio/src/components/Frame/index.js, packages/gatsby-theme-aio/src/components/Layout/index.js
This fixes a timeout issue with the penpal library.
This PR fixes an issue where `connectToChild` could be called after the child's `connectToParent` in the `Frame` component. This caused a child in the `Frame` to time out during connecting, as `coonnectToChild` must be called first as per API docs.
Tested to work with https://github.com/AdobeDocs/photoshop-api
DEVSITE-378
=> fix(DEVSITE-378): penpal timeout in Frame

packages/gatsby-theme-aio/src/components/CodeBlock/index.js, packages/gatsby-theme-aio/src/components/Tabs/index.js
Added support for keyboard navigation in CodeBlock.
Enabling tab switching and overflow scroll within CodeBlock with arrow buttons.
This was based on fixes applied by the Document Services team in their shadowed components.
In addition adjusted the colour of line number to improve contrast ratio.
This fixes reported accessibility issues in our CodeBlock.
Primarily tested by running scans for accessibility issues using AXE dev tools on /guides/reporting_api/#time-series-reports path of example folder.
=> CodeBlock keyboard support and colour contrast fixes

.github/workflows/e2e-tests.yml, cypress.config.js, cypress/cypress-github-actions.json, package.json
Fixed e2e test so that it runs gatsby develop (dev) on port 8000 instead of gatsby build && serve on port 9000. 
Fixing side effects of updating cypress packages to the latest versions.
Tested the cypress smoke test locally by running `yarn test:e2e`
=> fix: update test:e2e to run dev instead of build && serve

example/package.json, package.json, packages/gatsby-theme-aio/algolia/create-record.js, packages/gatsby-theme-aio/algolia/helpers/get-content-from-cache.js, packages/gatsby-theme-aio/algolia/helpers/get-iframe-content.js, packages/gatsby-theme-aio/algolia/helpers/get-openapi-content.js, packages/gatsby-theme-aio/algolia/helpers/get-products-indexes.js, packages/gatsby-theme-aio/algolia/index-records.js, packages/gatsby-theme-aio/algolia/index-settings.js, packages/gatsby-theme-aio/algolia/mdx-query.js, packages/gatsby-theme-aio/gatsby-node.js
This PR adds a `path` key to all the search record objects for use on the frontend. Additionally, this PR:
- Refactors our custom graphql schema code in `gatsby-node.js` to return defaults and ensure our custom types are being resolved correctly.
- Adds default return values (currently null) to `getProductFromIndex()` and `getIndexesFromProduct()` when there is no matching product or index passed in.
- Removes the product and index from the theme's example project.
The relative path property was found to be missing during frontend testing.
Ensuring frontend code has all the data it needs from the search records.
Ran updates again `example` project and monitored the results on Algolia servers.
Showing all record properties available to frontend:
=> fix: add path key with relative path to search records

packages/gatsby-theme-aio/algolia/helpers/html-parser.js, packages/gatsby-theme-aio/algolia/helpers/parse-mdx.js, packages/gatsby-theme-aio/gatsby-node.js
This PR reopens the theme's custom schema from consumer projects by allowing Gatsby to infer the schema as projects add to it.
Some projects that use the theme added additional schema nodes that require us to keep it open by letting Gatsby infer additional custom schema types.
Projects that add their own schema nodes are not permitted to do so when the `@dontInfer` directive is added. The reason for adding this directive was to speed up build times. For full details, see: https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#opting-out-of-type-inference
Tested against all the projects that threw errors during reindexing.
=> fix: allow schema inferences from theme consumers

packages/gatsby-theme-aio/gatsby-config.js
This PR fixes a mistaken name change to the `apiKey` of the `gatsby-plugin-algolia` plugin within the `gatsby-config.js` file. 
I am not aware of any related Jira issue. Please create one and add it here if there is not one already.
About two hours ago, Jeff made me aware that indexing was not working when deploying a site from the GitHub deploy workflow. So I saw the issue after examining the log of a test deployment and seeing this line: https://github.com/AdobeDocs/commerce-frontend-core/actions/runs/3145717529/jobs/5113345044#step:10:74
We've all seen and discussed this `.env` variable problem before: `api key or appId are missing; skipping ***ing`. After discovering that, the `.env` variable name mismatch between the `gatsby-config.js` and the GitHub action secret became the first …
=> fix: fix apiKey name to match name in deploy.yml

packages/gatsby-theme-aio/src/components/SideNav/index.js
Adding a indicator to show there is nested items
Adding a chevron right icon that will display only when there is item to show when there is nested items.  It will rotate with when it is expand or collapse.  
It's a new feature requested by the mobile team to show the nested items with indictor. 
I linked my change to the mobile sdk pages to make sure the indicator shows up properly. 
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
=> Adding nested indicator for sideNav.

packages/gatsby-theme-aio/src/components/Frame/index.js
Fixes issue where `Frame` component no longer supported relative pathnames like `/include.html`.
Since this change: https://github.com/adobe/aio-theme/pull/833/files#diff-e7e3bc67be10b26102ec899e870d38cde494b9618cda1c96edb9e5d508364410R56 , the frame component crashed when used with a pathname like `/include.html` instead of `https://complete.path.to/include.html`.
https://jira.corp.adobe.com/browse/DEVSITE-600
Bug report following https://cq-dev.slack.com/archives/C01GU3V8XE0/p1668099022338219
Tested with the repository where the bug was discovered: https://github.com/AdobeDocs/commerce-webapi/pull/55/files now works as intended on the page `/graphql/reference/`
=> fix(DEVSITE-600): frame no longer supported relative paths

packages/gatsby-theme-aio/src/components/Breadcrumbs/index.js, packages/gatsby-theme-aio/src/components/MDXFilter/index.js
when it is a header, do not add a breadcrumb.  Also if it's the same title and same path, we will not add a breadcrumb as well. 
Need to make sure when it is a header, do not add a breadcrumb.  Also if it's the same title and same path, we will not add a breadcrumb as well.  
https://jira.corp.adobe.com/browse/DEVSITE-426
Tested with the two other repo in mobile sdks and photoshop api.
=> Fix Double Breadcrumb issue

packages/gatsby-theme-aio/src/components/GlobalHeader/index.js, packages/gatsby-theme-aio/src/components/SideNav/index.js
Make sure Collapse and Expand works when the user click on the menu. 
The side nav bar was not able to collapse and expand properly.  The fix is to make sure the click on the menu will collapse and expand will make sure it's being collapsed and expanded every click.
https://jira.corp.adobe.com/browse/DEVSITE-426
The 
I've deploy my changes locally to the other repos such as mobile sdk and uxp repos.
=> Enhancement for Side Nav bar.

packages/gatsby-theme-aio/src/components/AnnouncementBlock/index.js
The Annoucement block is not taking the style and variants in when it's internal links. 
Fix the problem by making sure the style and variants aren't an array.
=> annoucement button fix

packages/gatsby-theme-aio/src/components/Footer/index.js
The css of focus on the link of cookie preference text-decoration is being override from the third party style. 
Put inline css style to try override back the style so the when it's in focus, it'll should double underline.
https://jira.corp.adobe.com/browse/A11Y-5429
=> update cookie preference keyboard

packages/gatsby-theme-aio/src/components/Tabs/index.js
The horizontal tab is not scrolling properly with the new release.
The tabitems are inserted with a mobileTabView which makes the tabitems not after one another.
=> Fix the tab not scrolling issue

packages/gatsby-theme-aio/src/components/Search/index.js
This is a simple debouncing fix to reduce number of queries made as a result of queries made onchange of input bar.
500ms delays between attempts seemed to be a decent middle ground between reducing queries and the user experience.
Currently logging query count to console for testing.
We're worried about exceeding our Algolia plan's budget for actions which primarily consists of multi index queries.
=> Added simple debouncing to search suggestions to reduce queries while user is typing 

packages/gatsby-theme-aio/src/components/GatsbyLink/index.js
GatsbyLink is replacing all path structure which is same pathPrefix. 
The fix needs to be only for mobile sdk team where the pathPrefix is client-sdks then it will not replace the path structure. 
https://jira.corp.adobe.com/browse/DEVSITE-636
=> specific fix for mobile-sdk team's path structure.

packages/gatsby-theme-aio/src/components/Search/index.js
This fixes the bug where search frame's results links wouldn't target the top (parent) frame for links . Additionally minor css fix to center the clear input button.
=> fix: search results missing link retarget, clear button center css

packages/gatsby-theme-aio/src/components/InlineNestedAlert/index.js
Nested Inline alert icon and margin top is not aligned. 
Fix the css to align the icon and the text.
=> NestedInlineAlert fix with margin top

.github/workflows/e2e-tests.yml, package.json, yarn.lock
This PR fixes the broken E2E tests. 
Last week, GitHub switched their default Node.js version from 16 to 18 in all hosted runners. In Node 17, the node team stopped accepting the IPv4 localhost address (127.0.0.1) by default. So the [cypress.io](http://cypress.io/) action (v4) broke when localhost was used. The cypress team has not fixed the issue yet, but I have updated the cypress.io action to v5 in anticipation of a later fix.
The current workaround: Use the IPv6 localhost instead. For us, that means updating the `e2e-tests.yml` file to use `http://[::1]:9000` instead of `http://127.0.0.1:9000`.
E2E tests no longer break.
=> Fix E2E tests

packages/gatsby-theme-aio/algolia/index-records.js
Algolia record size limit is 20000 bytes with our current plan and pushing a larger record will result in an error which will stop the indexing operation.
This PR adds a size check before adding record to final records list and logs a warning mentioning which records will be skipped.
=> Fix: add skip for records exceeding our algolia limit

packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/Table/index.js, packages/gatsby-theme-aio/src/utils/index.js, yarn.lock
Table will now assign the same width as our main content column (`MOBILE_SCREEN_WIDTH`) by default and immediately starts observing the parent element for size changes using `useParentSize` util. If the parent element width is not 0 it will resize the Table to match.
I added `useParentSize` which is based on this [package's](https://github.com/dagda1/cuttingedge/blob/main/packages/use-get-parent-size/src/useParentSize/useParentSize.ts) code but stripped down from TS and modified to actually grab the parent elements size from the Table ref.
DEVSITE-755
Table wasn't resizing correctly when nested in a parent element with fickle width size.
Tested in the example and aep-mobile-sdk pages with tables.
=> fix: table not responding to parent size change

packages/gatsby-theme-aio/src/components/Table/index.js
When only one child (`{ }`) is passed to `children` prop it can be either `{ }` or `[{ }]` depending on how it was passed.
This is done for performance and consistent type reasons between rerenders. Changing the length check to isArray check to include this edge case.
=> fix: check for isArray instead

packages/gatsby-theme-aio/algolia/index-records.js
Added a reporting step to pass/fail pages based on frontmatter completion.
Currently checking for title, description, keywords as they're the essential for search results.
Tested example locally as part of the console only index run with no indices sent to algolia.
Example of starting and fail messages 
Example of pass message
=> feat: added a frontmatter reporting step to algolia indexing

packages/gatsby-theme-aio/algolia/index-records.js, packages/gatsby-theme-aio/gatsby-config.js
MOdified formatting to log warnings instead of fails per page with a final total displayed as a warn or error based on if it's a dry run or not. i.e console or index mode.
index mode:
console mode:
=> feat: improved the report format and custom logs when isDryRun

README.md, packages/gatsby-theme-aio/algolia/index-records.js, packages/gatsby-theme-aio/algolia/mdx-query.js, packages/gatsby-theme-aio/gatsby-node.js
Added support for flagging a page as noIndex.
Search index operation will ignore pages with `noIndex: true` in frontmatter.
This is a simple feature but important for repos with transcluded pages under `src/pages/` where we index all md pages by default. Currently such repos show duplicate results for the transcluded content in local search. The noIndex flag will help with removing these duplicates.
=> Ignore md pages when indexing if noIndex keyword set true

package.json, packages/gatsby-theme-aio/package.json, yarn.lock
Updated theme `sharp` dep to 0.33.0 version.
Added resolutions at root package.json to enforce `sharp: 0.33.0` and `gatsby-sharp: 1.12.0`
These versions work as expected and don't error with latest `musl` package version of github action runner image for ubuntu 22.04 LTS
=> Update and enforce latest sharp and gatsby-sharp pkgs to solve deploy errors

README.md, packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/RedoclyAPIBlock/index.js
Add option to disable the `Try it` widget in `RedoclyApiBlock`
=> chore(release): publish@4.11.8

README.md, packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/RedoclyAPIBlock/index.js
[DEVSITE-1112](https://jira.corp.adobe.com/browse/DEVSITE-1112): Make expand level of json samples customizable
=> chore(release): publish@4.11.10

packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/MDXFilter/index.js
Fit `resources` in `main` so that `main` aligns correctly with `hero`
https://jira.corp.adobe.com/browse/DEVSITE-1116
Before:
- ![before](https://github.com/adobe/aio-theme/assets/120194874/ad40aa51-18cb-444d-af7e-38f809c3152b)
After:
- ![after](https://github.com/adobe/aio-theme/assets/120194874/d3d441ad-975c-4d85-92f7-86d1de29996c)
=> chore(release): publish@4.11.11

packages/gatsby-theme-aio/src/components/GetCredential/CredentialForm.js, packages/gatsby-theme-aio/src/components/GetCredential/MyCredential.js, packages/gatsby-theme-aio/src/components/GetCredential/NoDeveloperAccessError.js, packages/gatsby-theme-aio/src/components/GetCredential/Organization.js, packages/gatsby-theme-aio/src/components/GetCredential/PreviousCredential.js, packages/gatsby-theme-aio/src/components/GetCredential/PreviousProject.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/ChangeOrganizationContent.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/NestedAlertContent.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/RequestAccess.js, packages/gatsby-theme-aio/src/components/GetCredential/SignIn.js, packages/gatsby-theme-aio/src/components/GetCredential/index.js
=> build:added some design issue

README.md, packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/RedoclyAPIBlock/index.js
Enable adding of request interceptor to RedoclyAPIBlock
https://jira.corp.adobe.com/browse/DEVSITE-1190
Things I tried that didn't work:
1. https://redocly.com/docs/developer-portal/guides/reference-docs-hooks/#steps. The RedoclyAPIBlock setup doesn't work with this.
2. Also attempted to [dynamically import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) the callback function, placing it in the static folder, similar to how we place open api spec in the static folder so we can access them within gatsby:
```<RedoclyAPIBlock src="/redocly-test/openapi/openapi.yaml" requestInterceptorSrc="/redocly-test/_override/ReferenceDocsHooks.js" />```
But that resulted in the following error being thrown:
```Cannot find module …
```
=> feat: request interceptor

example/src/pages/credential/GetCredentialApiKey.js, example/src/pages/credential/GetCredentialOAuthS2s.js
=> --Updated helptext

packages/gatsby-theme-aio/algolia/create-record.js, packages/gatsby-theme-aio/algolia/helpers/html-parser.js, packages/gatsby-theme-aio/algolia/helpers/parse-mdx.js, packages/gatsby-theme-aio/algolia/index-records.js, packages/gatsby-theme-aio/gatsby-config.js
- Fix for record size calculation. Previously skipped indexing because size was larger than algolia's limit for records.
- Enabled partial updates in gatsby-plugin-algolia and configured contentDigest in html parser and mdx query for diff checking.
Note:
- Current uuid object ids make it difficult to match records and need to be redesigned for more partial update support. Will follow up with another PR.
=> Enable partial updates and fix algolia record size calculation

packages/gatsby-theme-aio/src/components/GetCredential/Service.js
If a user is working on the devsite and using the get credentials component and they logout from their account or switch to another account **in a different tab** (for example, by going to dev console), the get credential component starts throwing unknown error. I have fixed this by redirecting the user to the SUSI page if the API returns 401.
https://jira.corp.adobe.com/browse/IOC-7708
=> fix: IOC-7708 - redirect user to the signin page if API call returns 401

packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/MDXFilter/index.js
**Issue:** Even when there's room, Discover block limits itself two columns. For example
**Root-cause:** https://github.com/adobe/aio-theme/pull/1571
https://jira.corp.adobe.com/browse/DEVSITE-1154
https://jira.corp.adobe.com/browse/DEVSITE-1116
2-columns when page has side-nav:
- <img width="1728" alt="Screenshot 2024-07-30 at 8 02 59 PM" src="https://github.com/user-attachments/assets/298ea04c-b594-40c3-8a98-69d962816150">
3-columns when page has no side-nav:
- <img width="1728" alt="Screenshot 2024-07-30 at 8 02 41 PM" src="https://github.com/user-attachments/assets/4f26afa4-2048-424e-8659-d8f3ddf758e3">
Confirming no regressions on https://github.com/adobe/aio-theme/pull/1571 - i.e. hero is still aligned with overview + resources
- …
=> fix: maximize columns in discover block

packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/MDXFilter/index.js
Make feedback component sticky by applying changes from https://github.com/AdobeDocs/commerce-webapi/pull/269 to aio-theme
https://jira.corp.adobe.com/browse/DEVSITE-1070
- User engagement increased significantly with sticky feedback component [in an experiment done by commerce team](https://jira.corp.adobe.com/browse/COMDOX-887)
- Devsite-team decided to make this the default design for the Feedback/MDXFilter component in the aio-theme:
Desktop:
Mobile:
=> feat: sticky feedback component

cypress/e2e/get-credentials.cy.js, example/src/pages/credential/GetCredentialApiKey.js, example/src/pages/credential/GetCredentialOAuthS2s.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardClientDetails.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardImsOrgID.js, packages/gatsby-theme-aio/src/components/GetCredential/CredentialDetailsCard.js, packages/gatsby-theme-aio/src/components/GetCredential/PreviousProject.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnCredentialDetails.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnImsOrgID.js, packages/gatsby-theme-aio/src/components/GetCredential/index.js
Added Ims Org ID in the credential card
=> Ims Org ID

README.md
Fix example in readme for request interceptor
https://jira.corp.adobe.com/browse/DEVSITE-1190
Initially used the same syntax used as the [redocly example](https://redocly.com/docs/api-reference-docs/configuration/functionality#example-configuration-with-javascript-library) (see hooks BeforeOperationSummary), but that resulted in syntax error (because of the way we're passing the function as a string argument to RedoclyAPIBlock):
```
api-full/:11 Uncaught SyntaxError: Unexpected token '.'
at w (preact.module.js:159:106)
at x (preact.module.js:136:781)
at L (preact.module.js:278:174)
at x (preact.module.js:136:215)
at L (preact.module.js:278:174)
at N (preact.module.js:110:156)
```
Updating the readme with what works: https://github.com/adobe/aio-theme/pull/1588/files#diff-b335630551682c19a7 …
=> fix: readme for request interceptor

cypress/e2e/get-credentials.cy.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardAPIKey.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardAllowedOrigins.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardClientDetails.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardClientId.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardClientSecret.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardImsOrgID.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardOrganizationName.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardScopes.js, packages/gatsby-theme-aio/src/components/GetCredential/CredentialDetailsCard.js, packages/gatsby-theme-aio/src/components/GetCredential/MyCredential.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnAPIKey.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnAllowedOrigins.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnClientId.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnClientSecret.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnCredentialDetails.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnOrganizationName.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnScopes.js
=> Bug : Update the credential card dynamically

README.md, packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/RedoclyAPIBlock/index.js
Enable scrollYOffset config so user can adjust the top of the redocly page so that it doesn't overlap with the top nav.
https://jira.corp.adobe.com/browse/DEVSITE-1347
https://jira.corp.adobe.com/browse/DEVSITE-1308
Slack conversation: https://adobeio.slack.com/archives/C01GU3V8XE0/p1727220077882769
This serves two purposes:
- provide a quick fix for https://jira.corp.adobe.com/browse/DEVSITE-1347, while we haven't migrated to the next gen yet (where we're using layout grid, which better addresses the issue)
- fulfill request in https://jira.corp.adobe.com/browse/DEVSITE-1308 to add more configs to RedoclyAPIBlock so to retain same look and feel when migrating from portal to on-premise-license version
Page: https://developer-stage.adobe.com/redocly-test/api-full/#operation/getInventory …
=> feat: redocly scroll y offset

packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json
Issue: Tried cutting 4.14.11 release, but it turns out it already exists:
- <img width="1574" alt="Screenshot 2024-10-02 at 8 30 57 AM" src="https://github.com/user-attachments/assets/bd2069e5-693d-4229-b17b-0c52efceec98">
- https://www.npmjs.com/package/@adobe/gatsby-theme-aio/v/4.14.11
Fix: Use 4.14.12 instead
=> chore(release): publish@4.14.12

cypress/e2e/get-credentials.cy.js, example/src/pages/credential/GetCredentialApiKey.js, example/src/pages/credential/GetCredentialOAuthS2s.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardAPIKey.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardAllowedOrigins.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardClientDetails.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardClientId.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardClientSecret.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardImsOrgID.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardOrganizationName.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/CardScopes.js, packages/gatsby-theme-aio/src/components/GetCredential/CredentialDetailsCard.js, packages/gatsby-theme-aio/src/components/GetCredential/Icons.js, packages/gatsby-theme-aio/src/components/GetCredential/PreviousCredential.js, packages/gatsby-theme-aio/src/components/GetCredential/PreviousProject.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnAPIKey.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnAllowedOrigins.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnClientId.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnClientSecret.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnCredentialDetails.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnOrganizationName.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnScopes.js, packages/gatsby-theme-aio/src/components/GetCredential/index.js
=> Bugs : Credential component update

packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/gatsby-node.js, packages/gatsby-theme-aio/package.json
**Issue** 
A few repos are failing build with error "ReferenceError:document is not defined"
- create-embed-sdk: https://github.com/AdobeDocs/create-embed-sdk/actions/runs/11586131790/job/32281470877
- express-add-ons: https://github.com/AdobeDocs/express-add-ons/actions/runs/11589307950/job/32264563671
- ff-services-docs: https://github.com/AdobeDocs/ff-services-docs/actions/runs/11585209248/job/32253763987
**Fix** 
Ignore lottie during server-side rendering to avoid build error (similar to https://tonye.design/writing/window-document-not-defined-gatsby-build/)
**Test** 
- created an RC: https://github.com/adobe/aio-theme/blob/fix-lottie-build-failure/packages/gatsby-theme-aio/package.json#L3
- installed RC in a create-embed-sdk branch: …
=> chore(release): publish@4.14.14

example/src/pages/credential/GetCredentialOAuthS2s.js, packages/gatsby-theme-aio/src/components/GetCredential/PreviousCredential.js
=> Fix : Space issues on the return flow

packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/RedoclyAPIBlock/index.js
Prevent `RedoclyAPIBlock` from overflowing by setting `redocly_container` max width
https://jira.corp.adobe.com/browse/DEVSITE-1810
Tested with [4.15.2-rc3](https://github.com/adobe/aio-theme/releases/tag/%40adobe%2Fgatsby-theme-aio%404.14.20-rc3) on [redocly-test](https://github.com/AdobeDocs/redocly-test/blob/main/src/pages/overflow/without-layout-with-sidebar.md?plain=1) to mirror [Radu's file](https://github.com/AdobeDocs/experience-manager-apis/blob/main/src/pages/api/stable/assets/author/index.md?plain=1).
**Before:**
https://developer.adobe.com/experience-cloud/experience-manager-apis/api/stable/assets/author/
**After:**
https://developer-stage.adobe.com/redocly-test/overflow/without-layout-with-sidebar/
**Other test cases:**
| has layout | has sidebar | test | before | after |
| …
=> fix: redoclyapiblock overflow

README.md, example/gatsby-config.js, example/src/pages/api-2.md, packages/gatsby-theme-aio/src/components/RedoclyAPIBlock/index.js
API playgrounds rendered with the `RedoclyAPIBlock` usually load on pages with `layout: none`, which means that for a short amount of time the page is empty, showing only the top navigation and the footer. When the request to retrieve an OpenAPI definition takes too long it might give the users the impression that the API playground doesn't work at all.
This PR sets the `hideLoading` configuration option [0] to its default of `false`, but allows overrides based on component properties.
[0] - https://redocly.com/docs-legacy/api-reference-docs/configuration/functionality
https://github.com/adobe/aio-theme/issues/1638
See the "Expected Behavior" from https://github.com/adobe/aio-theme/issues/1638.
* manually by calling the JS code that renders an API definition with the correct settings on …
=> feat: added the redocly loading spinner for the RedoclyAPIBlock (fixes #1638)
