packages/gatsby-theme-parliament/src/components/OpenAPIBlock.js
Fixes: 
- the link text color
- the h2 underline color
- drop down color
- Action Button colors
- and removes text shadow from code
Does not fix anchor link in header. 
Waiting for feedback from Lise on the Accordion.
n/a
Address feedback on OpenApi page
Tested visually in Gatsby
=> More Redoc Updates

packages/gatsby-theme-parliament/src/components/OpenAPIBlock.js
Moves the link 🔗  to the end of the heading. Still trying to figure out how to display the #.
n/a
Adhere to Spectrum look and feel.
Running it in gatsby dev
=> 🐛  Anchor after heading

packages/gatsby-theme-parliament/src/components/OpenAPIBlock.js
Applies spectrum styles to response section.
Also fixes minor issue with button inside a table not having correct font.
n/a
Design team decided no colors in the response section.
Tested running gatsby dev 
Before:
After:
=> Spectrumify Response section in OpenAPI page

packages/gatsby-theme-parliament/src/components/CodeBlock/index.js, packages/gatsby-theme-parliament/src/components/Contributors/index.js, packages/gatsby-theme-parliament/src/components/Feedback/index.js, packages/gatsby-theme-parliament/src/components/GlobalHeader/index.js, packages/gatsby-theme-parliament/src/components/SideNav/index.js, packages/gatsby-theme-parliament/src/components/Tabs/index.js, packages/gatsby-theme-parliament/src/components/Variant/index.js
Fixes a11y warnings in code
n/a
Fixes a11y issues that could be found by our users.
The fixes remove warnings that show up in eslint/jsx-a11y and axe.
=> ♿  Fix a11y warnings

README.md
=> Update README for Analytics and Github Contributors

README.md
=> fix: add updated instructions for publishing to production

packages/gatsby-theme-aio/src/components/Layout/index.js
Hey @icaraps - there seems to be a small bug with how the ims loads and inits. If you:
1. sign in 
2. redirect back to page
3. profile loads
4. open new tab on same url
5. profile doesn't load despite it saying the user is actually signed in
It appears there were some issues with loading and initing ims so this pr should fix that by adding the onReady function.
=> Added onReady function for ims to better handle loading and initing

example/src/pages/frame-with-exteral-url.md, example/static/child.html, packages/gatsby-theme-aio/algolia/query-builder.js, packages/gatsby-theme-aio/algolia/records/create-records-for-embedded-content.js, packages/gatsby-theme-aio/algolia/records/create-records-for-frame.js, packages/gatsby-theme-aio/algolia/records/create-records-for-open-api.js, packages/gatsby-theme-aio/algolia/records/create-records-for-regular-content.js, packages/gatsby-theme-aio/algolia/records/load-content-by-url.js
https://jira.corp.adobe.com/browse/DEVSITE-92 Add support of "frame" directive
https://jira.corp.adobe.com/browse/DEVSITE-93 Add support of "OpenAPI" directive
=> feat(DEVSITE-91, DEVSITE-93): add support of "frame" directive / Add support of "OpenAPI" directive

packages/gatsby-theme-aio/algolia/query-builder.js, packages/gatsby-theme-aio/algolia/records/create-records-for-embedded-content.js, packages/gatsby-theme-aio/algolia/records/create-records-for-frame.js, packages/gatsby-theme-aio/algolia/records/create-records-for-open-api.js, packages/gatsby-theme-aio/algolia/records/create-records-for-regular-content.js, packages/gatsby-theme-aio/package.json, yarn.lock
https://jira.corp.adobe.com/browse/DEVSITE-93
=> feat(DEVSITE-93): add support of "OpenAPI" directive

packages/gatsby-theme-aio/algolia/query-builder.js, packages/gatsby-theme-aio/algolia/records/create-records-for-embedded-content.js, packages/gatsby-theme-aio/algolia/records/create-records-for-frame.js, packages/gatsby-theme-aio/algolia/records/create-records-for-open-api.js, packages/gatsby-theme-aio/algolia/records/create-records-for-regular-content.js, packages/gatsby-theme-aio/algolia/records/record-utils.js, packages/gatsby-theme-aio/package.json, yarn.lock
This PR fixes the inconsistent naming of the `distinct` attribute for records. All records now have the same distinct attribute called `pageID`. This PR also fixes other inconsistencies between the four record creation methods we currently use. I also created a `record-utils.js` to extract the duplicate code between the four record-creation classes.
The record attribute used for the Algolia `distinct` feature needs to be the same for ALL records in the index because only one attribute can be set as the distinct attribute for an index. Therefore, the records with distinct attributes that don't match the Algolia setting will show multiple results—which looks like duplicate results— from the same page. See screen shots below.
Rebuilt the `uxp-photoshop` index after making the change to show …
=> Record Consistency

packages/gatsby-theme-aio/algolia/query-builder.js, packages/gatsby-theme-aio/algolia/records/record-utils.js
https://jira.corp.adobe.com/browse/DEVSITE-107
=> fix(DEVSITE-107): remove dupicate index records

packages/gatsby-theme-aio/algolia/query-builder.js, packages/gatsby-theme-aio/algolia/records/record-utils.js, packages/gatsby-theme-aio/gatsby-config.js
Based of https://github.com/adobe/gatsby-theme-aio/pull/445
=> feat: enable Algola partial updates

packages/gatsby-theme-aio/algolia/query-builder.js, packages/gatsby-theme-aio/algolia/records/create-records-for-embedded-content.js, packages/gatsby-theme-aio/algolia/records/create-records-for-frame.js, packages/gatsby-theme-aio/algolia/records/create-records-for-open-api.js, packages/gatsby-theme-aio/algolia/records/create-records-for-regular-content.js, packages/gatsby-theme-aio/algolia/records/record-utils.js, packages/gatsby-theme-aio/gatsby-config.js
https://jira.corp.adobe.com/projects/DEVSITE/issues/DEVSITE-33
=> fix: algolia indexation

packages/gatsby-theme-aio/algolia/records/record-utils.js
https://jira.corp.adobe.com/browse/DEVSITE-124
=> fix(DEVSITE-124): search-Broken Titles

packages/gatsby-theme-aio/src/components/Picker/index.js
Not much to this... just uses `useEffect` to update the `options` array if `items` should change.
#503 
Described in #503
Manual testing using gatsby develop
=> fix(picker): update picker options array when items changes. fixes #503

packages/gatsby-theme-aio/gatsby-node.js, packages/gatsby-theme-aio/package.json, yarn.lock
For some reason webpack decided to get angry about not having tty and os
=> Fix: webpack polyfill error

packages/gatsby-theme-aio/src/components/GlobalHeader/index.js
This is a fix for iOS devices where the global nav bar's tabs container would hide the dropdown menu. It turns out that in Apple's mobile WebKit browser "[if a fixed element has a fixed overflow:hidden parent, this element will be hidden](https://stackoverflow.com/a/31738261)." 
Since "[on the iOS platform, Apple requires every browser to run on WebKit. Even Google Chrome is forced to use WebKit on iOS devices](https://9to5google.com/2021/05/03/ios-browsers-underpowered-apple/#:~:text=On%20the%20iOS%20platform%2C%20Apple,use%20WebKit%20on%20iOS%20devices.&text=That's%20a%20function%20that%20other,years%2C%20but%20Apple%20held%20back)," all browsers on iOS showcased this behaviour.
Although not well documented, this is a known bug according to this log on [WebKit …
=> fix: nav dropdown menu hidden on iPhone

packages/gatsby-theme-aio/src/components/Frame/index.js
=> feat(SITES-5061): enable adobe io parent frame to return client id

packages/gatsby-theme-aio/src/components/GlobalHeader/index.js
=> fix: header search button aria label

packages/gatsby-theme-aio/src/components/Tabs/index.js
Removed unused code and fixed the Tabs keyboard support.
Left unused code and introduced bug to Tabs component in previous PR
Tested in example directory with placeholder Tabs component.
=> Fixed Tabs component keyboard support

packages/gatsby-theme-aio/algolia/helpers/get-products-indexes.js
This PR corrects the mistaken release of 4.6.0, which did not contain the latest backend changes published in 4.5.5.
Local builds with example project.
=> fix: minor refactoring to overwrite npm version 4.6.0

packages/gatsby-theme-aio/gatsby-node.js, packages/gatsby-theme-aio/package.json, yarn.lock
DC merge failed to build. 
The changes involved in the CustomMenu Block where the graphql was not defnied properly in the gatsby-node.js
Also package.json needs to include lotti-web for the adobe-io package.
=> Fix the problem with DC Merge

example/src/pages/cloud_filter/index.md, packages/gatsby-theme-aio/src/components/MDXFilter/MDXBlocks.js, packages/gatsby-theme-aio/src/components/OldProductCardGrid/index.js
Fix the ProductCardGrid is not working properly with the old layout. 
Adding the old ProductCardGrid as <OldProductCardGrid> for any user that is using the old look and feel.
=> Adding the OldProductCardGrid

packages/gatsby-theme-aio/gatsby-node.js
Fix DC merge error on customMenuBlock
Changes to fix the array in the type.
=> DC merge fix on customMenuBlock

packages/gatsby-theme-aio/src/components/GlobalHeader/index.js
Fix the mobile nav strike through issue. 
Need to make sure it doesn't add the bottom padding. 
https://jira.corp.adobe.com/browse/DEVSITE-585
=> DEV-585 - fix mobile nav strikthrough issue.

packages/gatsby-theme-aio/src/components/Footer/index.js
Update the do not sell my personal information 
Change to Do not sell or share my personal information and the path to 'https://adobe.com/privacy/us-rights.html'
https://jira.corp.adobe.com/browse/DEVSITE-601
=> DEV-601 - change personal information

packages/gatsby-theme-aio/src/components/Footer/index.js
Accessibility fix on the footer issues. 
Added new description over a "View All" link 
Fix the tabindex for cookie preferences but it may need to be tested in stage before to see if any external code has written override our code. 
https://jira.corp.adobe.com/browse/A11Y-5428
https://jira.corp.adobe.com/browse/A11Y-5429
https://jira.corp.adobe.com/browse/A11Y-5430
=> DevSite-567 - footer accessibility fix

packages/gatsby-theme-aio/gatsby-config.js, packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/Layout/index.js, packages/gatsby-theme-aio/src/components/Search/index.js, yarn.lock
This PR focuses on search and includes the addition of communication pipeline between parent page and the iframed search. Search will now listen to a message event and with the parent's pathname. Search will compare the pathname with the new product index map structure hosted here: https://github.com/AdobeDocs/search-indices/blob/main/product-index-map.json.
Additionally this PR includes stage / prod env awareness for search and indexing to algolia through the addition of a local env var `GATSBY_ALGOLIA_INDEX_ENV_PREFIX` which can be anything custom but we will keep standard 'stage' and 'prod'. Any other * prefix will be considered for testing.
Add local search functionality to Franklin platform which iframes search.
Add testing and staging environment for algolia indices to avoid …
=> Add local product context to iframed search, stage / prod env awareness, and new location for product index map

packages/gatsby-theme-aio/src/components/Tabs/index.js
Adding back the fix to have 6 tabs visible. 
the 6 tabs visible were missed in the merge to DC components.
=> DC-merge-fix-tab

packages/gatsby-theme-aio/src/components/GlobalHeader/index.js, packages/gatsby-theme-aio/src/components/Menu/index.js, packages/gatsby-theme-aio/src/components/ProductCard/index.js, packages/gatsby-theme-aio/src/components/ProductCardGrid/index.js, packages/gatsby-theme-aio/src/components/Search/index.js, packages/gatsby-theme-aio/src/components/Tabs/index.js
https://jira.corp.adobe.com/browse/DEVSITE-561
This should fix tickets for the accessibilities for the home page. 
This PR should cover the following tickets: A11Y-5437, A11Y-5497, A11Y-5499, A11Y-5500, A11Y-5501, A11Y-5502, A11Y-5503, A11Y-5504, A11Y-5505, A11Y-5506
=> devsite 561 accessibility home page 

packages/gatsby-theme-aio/src/components/InlineNestedAlert/index.js, packages/gatsby-theme-aio/src/components/MDXFilter/MDXBlocks.js, yarn.lock
It needs to add a new component called InlineNestedAlert to resolve this problem
Any nested components to include an InlineAlert doesn't render properly.
Adding a new component to address this issue. 
https://jira.corp.adobe.com/browse/DEVSITE-523
https://jira.corp.adobe.com/browse/DEVSITE-359
=> Adding InlineNestedAlert

example/src/pages/index.md, packages/gatsby-theme-aio/src/components/InlineNestedAlert/index.js, packages/gatsby-theme-aio/src/components/MDXFilter/MDXBlocks.js, yarn.lock
Update an example into our pages. 
Adding an inline nested alert component into our pages.
=> devsite 523 inlinealerts

packages/gatsby-theme-aio/src/components/GlobalHeader/index.js
Global nav icon is missing
The profile check was misisng.
=> update global nav icon

packages/gatsby-theme-aio/src/components/GlobalHeader/index.js, packages/gatsby-theme-aio/src/components/InlineNestedAlert/index.js, yarn.lock
Bugs were found by the mobile sdk team
Bug was related to only 1 line in inline alert and header is set to false
=> Bug Fix for inline alerts

packages/gatsby-theme-aio/src/components/GlobalHeader/index.js, packages/gatsby-theme-aio/src/components/Menu/index.js, packages/gatsby-theme-aio/src/utils/index.js
removed dropdown visible while hover and added checkmark near to show which is being displayed
=> fix: header navBar hovering issue

packages/gatsby-theme-aio/src/components/Layout/index.js
=> fix: safari iframe visibility with opacity toggle

packages/gatsby-theme-aio/src/components/Footer/index.js
Adding developer distribution into footer 
https://jira.corp.adobe.com/browse/DEVSITE-669
=> Adding developer distribution into footer

packages/gatsby-theme-aio/conf/globals.js, packages/gatsby-theme-aio/src/components/Footer/index.js
Fixes issue where the desktop max width settings of 1060px caused pages with Hero component title to be too far right, and the footer too narrow. This had been changed from 1280px in [this previous comit in Nov '22](https://github.com/adobe/aio-theme/commit/e8013d0db6488055f4d1b6edb2bc0d8dff1f6730), so changing it back. 
To fix the title and footer placement when a Hero component is used (see screenshots that illustrate)
Tested it locally with the Developer Distribution docs site. 
These screenshots illustrate the issue:
Screenshots with it see to 1280px again:
=> Sets desktop max width back to 1280px

packages/gatsby-theme-aio/src/components/List/index.js, packages/gatsby-theme-aio/src/components/Table/index.js
Adding some space the tab and 
https://jira.corp.adobe.com/browse/DEVSITE-594
https://jira.corp.adobe.com/browse/DEVSITE-595
=> Adding some space to the list and table.

packages/gatsby-theme-aio/src/components/Layout/index.js
Layout was firing false positive signal to show search on any query parameter presence such as `?ref=signup`. Applied the `query` only check solution from other section of the Layout component.
=> fix: search false positive on any query parameters

packages/gatsby-theme-aio/src/components/GitHubActions/index.js
Modify the Github report an issue link and form. 
Change the body to title in the github linke 
https://jira.corp.adobe.com/browse/DEVSITE-682
=> change title from body

packages/gatsby-theme-aio/src/components/Code/index.js
Adding new languages for code highlights
Adding new languages for code highlights
https://jira.corp.adobe.com/browse/DEVSITE-663
=> Adding new languages for code highlights

packages/gatsby-theme-aio/src/components/MDXFilter/index.js
Check non-existing dates
Check non-existing dates
https://jira.corp.adobe.com/browse/DEVSITE-717
=> Check non-existing dates

packages/gatsby-theme-aio/src/components/GlobalHeader/index.js, packages/gatsby-theme-aio/src/components/Layout/index.js, packages/gatsby-theme-aio/src/components/SideNav/index.js
=> fixed checkmark padding issue on the navbar

example/src/pages/miniresource_block/index.md, example/src/pages/textblock/textblock.md, packages/gatsby-theme-aio/src/components/TextBlock/index.js
=> fix: fixed the issue on text block

example/src/pages/index.md, packages/gatsby-theme-aio/src/components/Table/index.js
Simple bugfix for Table component which errors when a table has a single column.
=> Table errors with single column fix

example/src/pages/index.md, packages/gatsby-theme-aio/src/components/Media/index.js
Adobe TV link should be display as a video control.  
Adobe TV link needs to be displayed as an iframe if it's not a video type.  I've also removed the width to be 100% as then the user can specified whatever they like.  
https://jira.corp.adobe.com/browse/DEVSITE-275
=> Update media to use iframe

packages/gatsby-theme-aio/src/components/Code/index.js
update on code block to not include line number and copy button css
update on code block to not include line number and copy button css
https://jira.corp.adobe.com/browse/DEVSITE-617
=> update on code block

packages/gatsby-theme-aio/src/components/Layout/index.js, packages/gatsby-theme-aio/src/components/SideNav/index.js
Adding missing version for mobile
Adding missing version for mobile
https://jira.corp.adobe.com/browse/DEVSITE-704
=> update missing version in mobile

packages/gatsby-theme-aio/src/components/CodeBlock/index.js, packages/gatsby-theme-aio/src/components/OnThisPage/index.js
Removing headings onthispage if it's same as the codeblock headings
Removing headings onthispage if it's same as the codeblock headings
https://jira.corp.adobe.com/browse/DEVSITE-786
=> Remove headings if same as codeblock headings

packages/gatsby-theme-aio/src/components/GlobalHeader/index.js
Nav Bar has a gap after selection
make the top to be fixed position
https://jira.corp.adobe.com/browse/DEVSITE-766
=> Making the Top of menu set properly

packages/gatsby-theme-aio/src/components/Tabs/index.js
Update the padding bottom for tabblocks so be shorter
https://jira.corp.adobe.com/browse/DEVSITE-597
=> Update the padding bottom for tabblocks

packages/gatsby-theme-aio/src/components/Context/index.js, packages/gatsby-theme-aio/src/components/Image/index.js, packages/gatsby-theme-aio/src/components/Table/index.js
Change the image size in table to use max-Width instead 
Change the image size in table to use max-Width instead 
https://jira.corp.adobe.com/browse/DEVSITE-592
=> Update with changes to image size

packages/gatsby-theme-aio/src/components/Layout/index.js
Update the SideNav visibility
Update the SideNav visibility
https://jira.corp.adobe.com/browse/DEVSITE-694
=> Update SideNav to response better

packages/gatsby-theme-aio/src/components/MiniResourceCard/index.js
=> --Fixed text issue on mini resource card

example/src/pages/credential/GetCredentialExternal.js, packages/gatsby-theme-aio/src/components/GetCredential/CredentialForm.js, packages/gatsby-theme-aio/src/components/GetCredential/MyCredential.js, yarn.lock
=> fix: links

packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json
Update version to 4.10.6
Update version to 4.10.6
=> Update version to 4.10.6

packages/gatsby-theme-aio/src/components/GetCredential/ChangeOrganization.js, packages/gatsby-theme-aio/src/components/GetCredential/ContextHelp.js, packages/gatsby-theme-aio/src/components/GetCredential/CredentialForm.js, packages/gatsby-theme-aio/src/components/GetCredential/FormFields.js, packages/gatsby-theme-aio/src/components/GetCredential/JoinBetaProgram.js, packages/gatsby-theme-aio/src/components/GetCredential/MyCredential.js, packages/gatsby-theme-aio/src/components/GetCredential/SignIn.js, packages/gatsby-theme-aio/src/components/GetCredential/index.js
=> fix(getcredential): fixed design issues

packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/GetCredential/ChangeOrganization.js, packages/gatsby-theme-aio/src/components/GetCredential/CredentialForm.js, packages/gatsby-theme-aio/src/components/GetCredential/ErrorBoundary.js, packages/gatsby-theme-aio/src/components/GetCredential/FormFields.js, packages/gatsby-theme-aio/src/components/GetCredential/IllustratedMessage.js, packages/gatsby-theme-aio/src/components/GetCredential/Loading.js, packages/gatsby-theme-aio/src/components/GetCredential/MyCredential.js, packages/gatsby-theme-aio/src/components/GetCredential/index.js, packages/gatsby-theme-aio/src/components/GlobalHeader/index.js
=> Bug get credentials org change

packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json
Update to release 4.10.7
Update to release 4.10.7
=> Louisa/release 4.10.7

packages/gatsby-theme-aio/src/components/Footer/index.js
Update global footer. 
https://jira.corp.adobe.com/browse/DEVSITE-738
=> Update global footer

packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json
Update package.json for release 4.11.1
=> Chore(release)-publish@4.11.1

packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json
=> update release build

packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json
- Added Mini Product Resources card
- Added video in the Hero Block
- Modified the design in accordion
=> chore(release): publish@4.11.9

packages/gatsby-theme-aio/src/components/GetCredential/CredentialForm.js, packages/gatsby-theme-aio/src/components/GetCredential/Loading.js
=> Create Credentials Page load

README.md, packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/RedoclyAPIBlock/index.js
Add `generateCodeSamples` configuration option to `RedoclyAPIBlock`
https://developer-stage.adobe.com/redocly-test/api-full/
- <img width="1073" alt="Screenshot 2024-06-14 at 7 54 08 PM" src="https://github.com/adobe/aio-theme/assets/120194874/ee25612c-39f3-43fd-afd8-f1c82d327a9f">
- <img width="1656" alt="Screenshot 2024-06-14 at 7 50 25 PM" src="https://github.com/adobe/aio-theme/assets/120194874/4047d3de-acf0-44b7-be15-a38d7244192b">
=> feat: generate code samples

packages/gatsby-theme-aio/src/components/GlobalHeader/index.js, packages/gatsby-theme-aio/src/components/Layout/index.js, packages/gatsby-theme-aio/src/components/SideNav/index.js
=> Hamburger Issue

packages/gatsby-theme-aio/src/components/GetCredential/CredentialForm.js, packages/gatsby-theme-aio/src/components/GetCredential/Form/AllowedOrigins.js, packages/gatsby-theme-aio/src/components/GetCredential/Form/CredentialName.js, packages/gatsby-theme-aio/src/components/GetCredential/FormFields.js
=> Error in form

packages/gatsby-theme-aio/src/components/GetCredential/Card/AccessToken.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/ShowCard.js
=> --Fixed the issues on the generate token & client secret

packages/gatsby-theme-aio/src/components/GetCredential/PreviousProject.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ProjectsDropdown.js
=> Fix : project name issues in the return flow

packages/gatsby-theme-aio/src/components/GetCredential/Organization.js
=> fix : Updated role text in the organization

packages/gatsby-theme-aio/src/components/GetCredential/Organization.js
=> Fix : Picker design issues

packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/OrganizationAccessDetailsEdgeCase.js
=> fix: added email to request access

packages/gatsby-theme-aio/src/components/GetCredential/CredentialForm.js, packages/gatsby-theme-aio/src/components/GetCredential/Form/Download.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ProjectsDropdown.js
=> fix: dropdown similarity

packages/gatsby-theme-aio/src/components/GetCredential/Loading.js, packages/gatsby-theme-aio/src/components/GetCredential/index.js
=> fix: added loading text to the loader

packages/gatsby-theme-aio/src/components/GetCredential/CredentialForm.js, packages/gatsby-theme-aio/src/components/GetCredential/PreviousCredential.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/OrganizationAccessDetails.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/OrganizationAccessDetailsEdgeCase.js
=> fix: Personal Developer Org bug on org switcher and error states

packages/gatsby-theme-aio/algolia/create-record.js, packages/gatsby-theme-aio/algolia/helpers/html-parser.js, packages/gatsby-theme-aio/algolia/helpers/parse-html.js, packages/gatsby-theme-aio/algolia/helpers/parse-mdx.js, packages/gatsby-theme-aio/algolia/index-records.js, packages/gatsby-theme-aio/src/components/Search/index.js
- Update ObjectID formula for partial index matching and use MD file contentDigest when parsing html or mdx
- Add optional chaining for missing content/description errors in search results
=> Fix Aloglia record objectID formula for partial index matching && fix missing content errors with optional chaining

example/src/pages/credential/GetCredentialApiKey.js, packages/gatsby-theme-aio/src/components/GetCredential/CredentialDetailsCard.js
=> --Fixed the next button issues on the credential card & return flow

packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/GetCredential/Card/AccessToken.js, packages/gatsby-theme-aio/src/components/GetCredential/Card/ShowCard.js, packages/gatsby-theme-aio/src/components/GetCredential/Loading.js, packages/gatsby-theme-aio/src/components/GetCredential/Organization.js, packages/gatsby-theme-aio/src/components/GetCredential/Products.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/OrganizationAccessDetails.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/OrganizationAccessDetailsEdgeCase.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/RequestAccessModal.js, packages/gatsby-theme-aio/src/components/GetCredential/SignIn.js, packages/gatsby-theme-aio/src/components/GetCredential/index.js
=> --Migrated React spectrum to spectrum css

example/src/pages/credential/GetCredentialApiKey.js, example/src/pages/credential/GetCredentialOAuthS2s.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/OrganizationAccessDetailsEdgeCase.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/OrganizationAccessDetailsNoProduct.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/OrganizationAccessDetailsNotMember.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/OrganizationAccessDetailsNotSignUp.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/OrganizationAccessDetailsType1User.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/RequestAccess.js, packages/gatsby-theme-aio/src/components/GetCredential/RequestAccess/RestrictedAccessFields.js, packages/gatsby-theme-aio/src/components/GetCredential/index.js
=> --Made product name as dynamically

cypress/e2e/get-credentials.cy.js, example/src/pages/credential/GetCredentialApiKey.js, packages/gatsby-theme-aio/src/components/GetCredential/Organization.js
=> fix: fix failing tests

packages/gatsby-theme-aio/algolia/helpers/parse-mdx.js
Main fix of link text missing from search results by correctly mapping to the queried link's text value with
```
if (child.type === 'link') {
return child?.children?.find(child => child.type === 'text')?.value;
}
```
Some minor formatting fixes.
Tested within commerce-php repo where the issue was originally reported from by @dshevtsov
=> fix: link text not indexing

README.md, packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/RedoclyAPIBlock/index.js
Enable sorting by tags and operations in RedoclyAPIBlock
Slack: https://adobeio.slack.com/archives/C01GU3V8XE0/p1723620942344059
- [T0O0](https://developer-stage.adobe.com/redocly-test/sort-T0O0/): [unsorted tags, unsorted operations](https://github.com/AdobeDocs/redocly-test/blob/1a22ef2443c5ace6ee74ad9a9305ef130813df1c/src/pages/sort-T0O0/index.md?plain=1)
- [T0O1](https://developer-stage.adobe.com/redocly-test/sort-T0O1/): [unsorted tags, sorted operations](https://github.com/AdobeDocs/redocly-test/blob/1a22ef2443c5ace6ee74ad9a9305ef130813df1c/src/pages/sort-T0O1/index.md?plain=1)
- [T1O0](https://developer-stage.adobe.com/redocly-test/sort-T1O0/): [sorted tags, unsorted operations](https://github.com/AdobeDocs/redocly-test/blob/1a22ef2443c5ace6ee74ad9a9305ef130813df1c/src/pages/sort-T1 …
=> feat: redocly sort configs

README.md
=> docs: update gatsby link

example/src/pages/credential/GetCredentialApiKey.js, packages/gatsby-theme-aio/src/components/GetCredential/MyCredential.js
=> Feat : Add card collapsable

example/src/pages/credential/GetCredentialApiKey.js, example/src/pages/credential/GetCredentialOAuthS2s.js, packages/gatsby-theme-aio/src/components/GetCredential/PreviousCredential.js, packages/gatsby-theme-aio/src/components/GetCredential/PreviousProject.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnNewCredential.js, packages/gatsby-theme-aio/src/components/GetCredential/Return/ReturnSideComp.js
=> fix : credential design issues - remove padding

packages/gatsby-theme-aio/src/components/Footer/index.js, packages/gatsby-theme-aio/src/components/GlobalHeader/index.js, packages/gatsby-theme-aio/src/components/Layout/index.js, packages/gatsby-theme-aio/src/components/SEO/index.js, packages/gatsby-theme-aio/src/components/SideNav/index.js, packages/gatsby-theme-aio/src/components/Tabs/index.js, yarn.lock
=> feat: add in aep analytics

.github/workflows/e2e-tests.yml, cypress.config.js
Moving cypress user password to secret environment variables. I have created a new secret [here](https://github.com/adobe/aio-theme/settings/secrets/actions).
[VULN-31173](https://jira.corp.adobe.com/browse/VULN-31173)
=> feat: vuln-31173 - move cypress user password to secrets

packages/gatsby-theme-aio/CHANGELOG.md, packages/gatsby-theme-aio/package.json, packages/gatsby-theme-aio/src/components/Footer/index.js
Update Footer link for Adobe Developers Blog
https://jira.corp.adobe.com/browse/DEVSITE-1698
- [4.14.20-rc3](https://github.com/adobe/aio-theme/releases/tag/%40adobe%2Fgatsby-theme-aio%404.14.20-rc3)
- developer-stage.adobe.com
=> feat: update Footer link for Adobe Developers Blog
